// data.js - لغات و گرامر تمام پایه‌ها
const words={};
const grammar={};

// ========== آواها و صداها (پایه هفتم) ==========
words[0]=[["A a","اِی - آ - ا","Ali – Sara – name - many"],["B b","ب","Babak"],["E e","ئی - ِا","Ehsan"],["G g","ج - گ","girl - age"],["I i","ئی - ا","birthday - Iman"],["K k","ک","Kamal"],["M m","م","Matin"],["N n","ن","Naser"],["P p","پ","pen"],["S s","س - ز","Sasan - is"],["T t","ت","ten"],["U u","یو - ِا - آ","uncle - nurse - student"],["D d","د","door"],["L l","ل","lunch"],["R r","ر","red"],["F f","ف","farmer"],["V v","و (دندانی ته لب)","villa"],["W w","و (دندانی نوک لب)","woman"],["O o","اُا - آ - ِا","office – orange - pilot"],["H h","ه","hand"],["X x","اکس","six"],["Y y","ی - ئی - آی","yes – forty - sky"],["C c","ک - س","pencil - car"],["J j","ج","jelly"],["Q q","ک","quince"],["Z z","ز","zero"]];

// ========== پایه هفتم - درس 1 ==========
words[1]=[["What's your last name?","نام خانوادگی شما چیست؟"],["library card","کارت عضویت کتابخانه"],["I'm your English teacher.","من معلم زبان شما هستم"],["How are you?","حال شما چطور است؟"],["good afternoon","ظهر به خیر"],["Now, you tell me your names.","حال شما اسم‌هایتان را به من بگویید"],["stand up","بلند شدن"],["last name","نام خانوادگی"],["library","کتابخانه"],["and","و"],["name","نام"],["excuse me","ببخشید"],["fine","خوب"],["sit down","نشستن"],["Great, thanks.","خوبم، ممنون"],["hello","سلام"],["How do you spell ...?","... را چگونه هجی می‌کنیم؟"],["thank you","متشکرم"],["Mrs.","خانم"],["My name is ...","اسم من ... است"],["How do you spell your last name?","نام خانوادگی‌ات را چگونه هجی می‌کنی؟"],["first name","اسم کوچک"],["Fine, thanks.","خوبم، ممنون"],["please","لطفاً"],["teacher","معلم"],["What's your first name?","اسم (کوچک) شما چیست؟"],["Mr.","آقا"],["student","دانش‌آموز"],["Can you spell your name?","می‌توانی اسمت را هجی کنی؟"],["How are you today?","امروز حالتان چطور است؟"],["good morning","صبح به خیر"],["I'm ...","من ... هستم"],["class","کلاس"],["hi","سلام"],["Now, please say your name.","حالا لطفاً اسمتان را بگویید"],["one by one","یکی یکی"],["thanks","ممنون"],["Miss","خانم"]];
grammar[1]=[["نکته اول: بزرگ نوشتن حرف اول اسم و فامیل","در نوشتن اسم و فامیل همیشه اولین حرف را بزرگ می‌نویسیم.","Narges Ebrahimi (درست) - narges ebrahimi (نادرست)","حرف اول اسم کوچک و نام خانوادگی باید با حرف بزرگ نوشته شود."],["نکته دوم: لقب‌های احترام‌آمیز","برای آقایان از Mr. و برای خانم‌های متاهل از Mrs. و برای خانم‌های مجرد از Miss استفاده می‌شود.","Mr. Smith - Mrs. Johnson - Miss Davis","برای احترام گذاشتن از لقب‌های جداگانه استفاده می‌شود."],["نکته سوم: کلمه پرسشی What","What به معنی «چه» است و برای پرسیدن نام افراد استفاده می‌شود.","What's your name? → اسم تو چیست؟","What's مخفف What is است."],["نکته چهارم: کلمه پرسشی How","How به معنی «چطور» است و برای احوالپرسی استفاده می‌شود.","How are you? → حالت چطور است؟","How هم برای احوالپرسی و هم برای پرسش چگونگی استفاده می‌شود."]];

// ========== پایه هفتم - درس 2 ==========
words[2]=[["classmate","هم‌کلاسی"],["who","چه کسی"],["this","این (اشاره به نزدیک)"],["that","آن (اشاره به دور)"],["boy","پسر"],["new","جدید"],["talk","صحبت کردن"],["him","او را، به او، با او"],["nice","خوب"],["meet","ملاقات کردن"],["our","ـِـ ما"],["welcome","خوش آمد گفتن"],["school","مدرسه"],["friend","دوست"],["Thank you.","ممنون از شما"],["too","همچنین"],["girl","دختر"],["man","مرد"],["woman","خانم"],["she","او (مؤنث)"],["he","او (مذکر)"],["can","توانستن"],["help","کمک کردن"],["have","داشتن"],["please","لطفاً"],["library","کتابخانه"],["library card","کارت کتابخانه"],["sure","حتماً"],["sorry","متاسفم"],["again","دوباره"],["librarian","کتابدار"],["teacher","معلم"],["student","دانش‌آموز"]];
grammar[2]=[["کلمه پرسشی Who","Who به معنی «چه کسی» برای سوال در مورد اشخاص به کار می‌رود.","Who is that man? → آن مرد کیست؟","Who برای پرسیدن درباره هویت یک شخص استفاده می‌شود."],["کلمه پرسشی How / What","How/What به معنی «چطور/چه» هستند.","What's your sister's name? / How are you?","What برای پرسیدن اسم و How برای احوالپرسی."],["مخفف کلمات","برای راحت کردن حرف زدن از مخفف استفاده می‌شود.","I am = I'm / You are = You're / he is = he's","مخفف‌ها در مکالمات روزمره رایج هستند."],["This / That برای معرفی","برای معرفی کسی از This/That به معنی «این/آن» استفاده می‌کنیم.","This is my friend Sina.\nThat is my classmate Sobhan.","This برای نزدیک و That برای دور."]];

// ========== پایه هفتم - درس 3 ==========
words[3]=[["date","تاریخ"],["twelve","دوازده"],["ten","ده"],["March","مارس"],["eleven","یازده"],["six","شش"],["no","نه"],["forty","چهل"],["September","سپتامبر"],["fifty","پنجاه"],["fifteen","پانزده"],["thirteen","سیزده"],["sixty","شصت"],["really","واقعاً"],["seventy","هفتاد"],["When is your birthday?","روز تولد شما کی است؟"],["fourteen","چهارده"],["eighty","هشتاد"],["Friday","جمعه"],["How do you say this word?","این واژه را چگونه (به انگلیسی) می‌گوییم؟"],["ninety","نود"],["Sunday","یکشنبه"],["It's my birthday today.","امروز تولد من است"],["sixteen","شانزده"],["twenty","بیست"],["seventeen","هفده"],["Wednesday","چهارشنبه"],["Monday","دوشنبه"],["one hundred","یک صد"],["eighteen","هجده"],["What about you?","شما چطور؟"],["My birthday is in ...","تولد من در (ماه) ... است"],["August","اوت"],["nineteen","نوزده"],["I'm ... years old.","من ... ساله هستم"],["May","مه"],["birthday","روز تولد"],["two","دو"],["nine","نه"],["three","سه"],["months of the year","ماه‌های سال"],["four","چهار"],["January","ژانویه"],["five","پنج"],["Tuesday","سه‌شنبه"],["happy birthday","تولدت مبارک"],["Saturday","شنبه"],["July","ژوئیه"],["one","یک"],["eight","هشت"],["Thursday","پنج‌شنبه"],["How old are you?","چند سال دارید؟"],["age","سن"],["Oh, I see.","اوه، متوجه شدم"],["April","آوریل"],["seven","هفت"],["June","ژوئن"],["year","سال"],["How old is your brother?","برادر شما چند ساله است؟"],["November","نوامبر"],["October","اکتبر"],["thirty","سی"],["December","دسامبر"]];
grammar[3]=[["بزرگ نوشتن حرف اول جمله","اولین حرف جمله را هم مانند اول اسم و فامیل بزرگ می‌نویسیم.","My name is Amirreza.","در انگلیسی، اولین حرف هر جمله با حرف بزرگ نوشته می‌شود."],["کلمه پرسشی When","When به معنی «کی / چه وقتی» برای پرسش از زمان به کار می‌رود.","When is your mother's birthday?","در پاسخ از ماه تولد یا on + تاریخ استفاده می‌شود."],["کلمه پرسشی How old","How old به معنی «چند سال» است و برای پرسش سن به کار می‌رود.","How old are you?","برای پاسخ از I am + سن + years old استفاده می‌شود."]];

// ========== پایه هفتم - درس 4 ==========
words[4]=[["aunt","خاله/عمه/زن عمو/زن دایی"],["shopkeeper","مغازه‌دار"],["employee","کارمند"],["wife","همسر"],["What is your mother's job?","شغل مادر شما چیست؟"],["number","عدد"],["driver","راننده"],["pilot","خلبان"],["baker","نانوا"],["job","شغل"],["waiter","پیشخدمت (آقا)"],["Is that your father?","آیا او پدر شماست؟"],["florist","گل‌فروش"],["postman","پستچی"],["son","فرزند پسر"],["brother","برادر"],["How old is he?","او چند ساله است؟"],["grandmother","مادربزرگ"],["daughter","فرزند دختر"],["worker","کارگر"],["picture","تصویر"],["uncle","عمو/دایی/شوهرخاله/شوهرعمه"],["housewife","خانم خانه‌دار"],["What is your father's name?","اسم پدر شما چیست؟"],["family","خانواده"],["What's your father's job?","شغل پدر شما چیست؟"],["teacher","معلم"],["farmer","کشاورز"],["Can you write it for me, please?","می‌توانید لطفاً این را برای من بنویسید؟"],["sister","خواهر"],["mother","مادر"],["How old is your ...?",".... شما چند ساله است؟"],["nurse","پرستار"],["dentist","دندانپزشک"],["engineer","مهندس"],["nice","خوب"],["mechanic","مکانیک"],["grandfather","پدربزرگ"],["What's his job?","شغل او چیست؟"],["How do you spell your first name?","اسم کوچک‌تان را چگونه هجی می‌کنید؟"],["painter","نقاش"],["cook","آشپز"],["He's ... years old.","او ... ساله است"],["He's a ...","پدر من یک ... [شغل] است"],["father","پدر"],["policeman","پلیس"],["doctor","دکتر"]];
grammar[4]=[["صفات ملکی","صفاتی که قبل اسم می‌آیند و مالکیت را نشان می‌دهند.","My = مال من / Your = مال شما / His = مال او (مذکر)\nHer = مال او (مؤنث) / Its = مال آن / Their = مال آنها","صفات ملکی قبل از اسم می‌آیند."],["مالکیت با 's","برای نشان دادن مالکیت با کلمه 's استفاده می‌شود.","What's her uncle's name?","برای اشخاص از 's استفاده می‌شود."],["کلمه پرسشی What برای شغل","What برای پرسیدن شغل افراد استفاده می‌شود.","What's your aunt's job?","What برای پرسش درباره شغل."],["سوالی کردن جمله","برای سوالی کردن، فعل کمکی (am/is/are) را به اول جمله می‌آوریم.","Is that your father?","در پاسخ از Yes/No استفاده می‌کنیم."]];

// ========== پایه هفتم - درس 5 ==========
words[5]=[["tall","بلندقد"],["grey","طوسی"],["white","سفید"],["manteau","مانتو"],["hat","کلاه"],["chador","چادر"],["glove","دستکش"],["Is that your English teacher?","آیا او معلم زبان شما است؟"],["green","سبز"],["young","جوان"],["math","ریاضی"],["orange","نارنجی"],["pink","صورتی"],["belt","کمربند"],["sunglasses","عینک آفتابی"],["suit","کت شلوار"],["T-shirt","تی شرت"],["He's wearing a grey suit.","او یک کت و شلوار طوسی پوشیده است"],["brown","قهوه‌ای"],["He's over there.","او آنجا (ایستاده) است"],["blue","آبی"],["sock","جوراب"],["dress","پیراهن زنانه"],["shoe","کفش"],["black","سیاه"],["shirt","پیراهن"],["sweater","ژاکت"],["No, my English teacher is the tall man.","نه، معلم انگلیسی من آن مرد بلندقد است"],["glasses","عینک"],["short","قدکوتاه"],["Let's meet your English teacher first.","بیا ابتدا با معلم انگلیسی شما ملاقات کنیم"],["old","پیر"],["coat","پالتو"],["trousers","شلوار"],["red","قرمز"],["yellow","زرد"],["jacket","کت"],["He's wearing a blue suit and a white shirt.","او یک کت و شلوار آبی و پیراهن سفید پوشیده است"],["sandal","صندل"],["And which one is your math teacher?","و کدام یکی معلم ریاضی شماست؟"],["wear","پوشیدن"]];
grammar[5]=[["کلمات پرسشی Which one / Who","Who/Which one به معنی «چه کسی / کدام یک» برای شناختن افراد بر اساس ظاهر و لباس.","Who is Mr. Rafiei?\nWhich one is your mom?","Who برای پرسش هویت و Which one برای انتخاب."],["ساختار wearing برای لباس","از کلمه wearing به معنی «پوشیدن» برای بیان لباس استفاده می‌شود.","She is wearing a red scarf.","ساختار: فاعل + am/is/are + wearing + مفعول"],["سوالی کردن با am/is/are","یکی از راه‌های سوالی کردن استفاده از افعال کمکی am/is/are است.","Is that your uncle?","در جواب از Yes/No استفاده می‌کنیم."],["پاسخ بر اساس ظاهر و لباس","در پاسخ به سوال Who و Which one بر اساس ظاهر و لباس جواب می‌دهیم.","Ali is the tall boy.\nHe is wearing a white shirt.","برای لباس از ساختار am/is/are + wearing استفاده می‌شود."]];

// ========== پایه هفتم - درس 6 ==========
words[6]=[["watch TV","تلویزیون تماشا کردن"],["again","دوباره"],["where","کجا"],["bedroom","اتاق خواب"],["work","کار کردن"],["car","ماشین"],["bathroom","حمام"],["cook","پختن"],["blanket","پتو"],["correct","صحیح"],["bookcase","قفسه کتاب"],["dad","بابا"],["clock","ساعت دیواری"],["do","انجام دادن"],["comb","شانه"],["fix","تعمیر کردن"],["computer","کامپیوتر"],["for","برای"],["drink","نوشیدن"],["garage","پارکینگ"],["eat","خوردن"],["house","خانه"],["flat/apartment","آپارتمان"],["hungry","گرسنه"],["kitchen","آشپزخانه"],["I'll call dad","من پدر را صدا خواهم کرد"],["mirror","آینه"],["living room","اتاق پذیرایی"],["newspaper","روزنامه"],["look at","نگاه کردن به"],["play","بازی کردن"],["lunch","ناهار"],["radio","رادیو"],["mom","مامان"],["stairs","راه پله"],["office","دفتر شرکت"],["study","مطالعه کردن"],["picture","تصویر"],["table","میز ناهارخوری"],["play football","فوتبال بازی کردن"],["television","تلویزیون"],["read a book","کتاب خواندن"],["tower","برج"],["say","گفتن"],["villa","ویلا"],["so","خیلی"],["Wash your hands","دست‌هایت را بشور"]];
grammar[6]=[["زمان حال استمراری","بیان کاری که هم اکنون در جریان است.","My Dad is fixing the car.","ساختار: Am / is / are + فعل + ing"],["سوالی کردن حال استمراری - روش اول","یکی از افعال am/is/are را به اول جمله می‌آوریم.","Is your dad fixing the car?","در جواب Yes یا No داریم."],["سوالی کردن حال استمراری - روش دوم","یکی از کلمات پرسشی مثل What را ابتدای جمله به کار می‌بریم.","What is your Dad doing?","در جواب نیازی به Yes یا No نداریم."],["کلمه پرسشی Where","Where به معنی «کجا» برای پرسیدن مکان به کار می‌رود.","Where is your mom?","Where برای پرسش درباره مکان."]];

// ========== پایه هفتم - درس 7 ==========
words[7]=[["39 Kargar Street, Baharestan","بهارستان، خیابان کارگر، پلاک 39"],["live","زندگی کردن"],["I'm not sure.","مطمئن نیستم"],["go","رفتن"],["Call me before you go.","قبل از اینکه بروی به من زنگ بزن"],["Around 5 in the afternoon.","حدوداً ساعت 5 بعد از ظهر"],["telephone","تلفن"],["OK, bye.","باشه، خداحافظ"],["What time are they leaving?","آنها چه ساعتی می‌روند؟"],["evening","عصر"],["What's their address?","آدرس (منزل) آنها چیست؟"],["address","نشانی"],["mobile","تلفن همراه"],["24 Laleh Street, Sa'dieh","سعدیه، خیابان لاله، پلاک 24"],["5 Azadi Street","خیابان آزادی، پلاک پنجم"],["What's your address?","آدرس (منزل) شما چیست؟"],["Are you coming with me?","آیا تو با من می‌آیی؟"],["e-mail address","آدرس ایمیل"],["15 Shahid Hakim Street, Manzarieh","منظریه، خیابان شهید حکیم، پلاک 15"],["home","خانه"],["What time is he going?","ساعت چند قرار است برود؟"],["What's his mobile phone number?","شماره موبایل او چند است؟"],["67 Mahan Street","خیابان ماهان، پلاک 67"],["81 Farnam Street","خیابان فرنام، پلاک 81"],["What's her address?","آدرس (منزل) او چیست؟"],["street","خیابان"],["p.m.","بعد از ظهر"],["What's his address?","آدرس (منزل) او چیست؟"],["... is not well.","حال ... خوب نیست"],["call","زنگ زدن"],["What time is she coming back?","چه ساعتی بر می‌گردد؟"],["I'm not sure I can, but I'll try.","مطمئن نیستم بتوانم (بیایم)، اما سعی خواهم کرد"],["I'm going to visit him today.","من قرار است امروز به ملاقاتش بروم"],["number","عدد"],["I don't understand.","متوجه نمی‌شوم"],["time","زمان"],["What's ...'s home number?","شماره تلفن منزل ... چند است؟"],["Where do you live?","کجا زندگی می‌کنید؟"],["What time are you going?","ساعت چند قرار است بروی؟"],["a.m.","قبل از ظهر"],["What's their telephone number?","شماره تلفن آنها چند است؟"],["I don't know.","نمی‌دانم"],["What's your telephone number?","شماره تلفن شما چند است؟"],["What time is it?","ساعت چند است؟"],["My phone number is ...","شماره تلفن من ... است"],["What's her office phone number?","شماره تلفن دفتر او چند است؟"],["o'clock","ساعت"]];
grammar[7]=[["ساختار going to برای آینده","برای بیان قصد و نیت برای انجام کاری در آینده.","I am going to visit my friend today.","ساختار: Am / is / are + going to + فعل"],["سوالی کردن با going to - روش اول","یکی از افعال am/is/are را به اول جمله می‌آوریم.","Are you going to visit your friend today?","در جواب Yes یا No داریم."],["سوالی کردن با going to - روش دوم","یکی از کلمات پرسشی مثل What time را ابتدای جمله می‌آوریم.","What time are you going to visit your friend?","در جواب نیازی به Yes یا No نداریم."],["کلمه پرسشی What برای آدرس و تلفن","What برای پرسیدن آدرس، تلفن و ایمیل.","What's your address?","What برای پرسش درباره اطلاعات شخصی."],["کلمه پرسشی What time","What time به معنی «چه ساعت» برای پرسیدن ساعت.","What time is it?","What time برای پرسش درباره زمان دقیق."]];

// ========== پایه هفتم - درس 8 ==========
words[8]=[["What's your favorite food?","غذای مورد علاقه‌ی شما چیست؟"],["jelly","ژله"],["rice","برنج"],["Look, it's enough.","بین، دیگر بس است"],["spaghetti","اسپاگتی"],["orange","پرتقال"],["Let's take something to eat.","بیا یک چیز بخوریم"],["cheese","پنیر"],["potato","سیب‌زمینی"],["Ok, let's go to the kitchen.","باشه، بیا به آشپزخانه برویم"],["Let's have something to drink.","بیا یک چیز بنوشیم"],["kebab","کباب"],["bread","نان"],["date","خرما"],["egg","تخم‌مرغ"],["yogurt","ماست"],["fruit","میوه"],["I'd like some ...","من کمی ... می‌خواهم"],["What's your favorite drink?","نوشیدنی مورد علاقه‌ی شما چیست؟"],["like","دوست داشتن"],["Me too. Let's have some cake and milk.","منم همینطور. بیا کمی شیر و کیک بخوریم"],["What do you like to drink?","چی میل دارید بنوشید؟"],["I feel thirsty.","من احساس تشنگی می‌کنم"],["salad","سالاد"],["How about some cake and milk?","نظرت راجع به کمی کیک و شیر چیست؟"],["orange juice","آب پرتقال"],["I feel hungry.","من احساس گرسنگی می‌کنم"],["food","غذا"],["banana","موز"],["quince","به (میوه)"],["Let's take something to drink.","بیا یک چیز بنوشیم"],["cake","کیک"],["carrot","هویج"],["What do you like to eat?","چی میل دارید بخورید؟"],["Let's have something to eat.","بیا یک چیز بخوریم"],["feel","احساس کردن"],["chicken","مرغ"],["thirsty","تشنگی"],["Sounds good.","خوب به نظر می‌آید"],["coconut","نارگیل"],["honey","عسل"],["drink","نوشیدنی"],["milk","شیر"],["onion","پیاز"],["That's my favorite.","آن (غذا) مورد علاقه‌ی من است"],["I am hungry.","من گرسنه هستم"],["hungry","گرسنه"],["apple","سیب"],["water","آب"],["ice cream","بستنی"],["pineapple","آناناس"],["How do you say … in English?","... به انگلیسی چه می‌شود؟"],["zucchini","کدو سبز"],["favorite","مورد علاقه"],["I'm hungry. How about you?","من گرسنه هستم. تو چطور؟"],["juice","آبمیوه"],["enough","به اندازه کافی"],["fish","گوشت ماهی"],["I am thirsty.","من تشنه هستم"],["tea","چای"],["go shopping","به خرید رفتن"],["I'd like some tea with my cake.","من دوست دارم کمی چای با کیکم بخورم"],["tomato","گوجه"]];
grammar[8]=[["What + favorite برای غذا و نوشیدنی","کلمه پرسشی What به همراه favorite برای پرسیدن غذا و نوشیدنی مورد علاقه.","What's your favorite food / drink?","What + favorite + اسم برای پرسش درباره علایق."],["How about برای پیشنهاد","How about به معنی «چه طور» برای پیشنهاد چیزی به دیگران.","I am thirsty.\nHow about some orange juice?","How about برای ارائه پیشنهاد."],["Let's برای پیشنهاد انجام کار","Let's (مخفف Let us) به معنی «اجازه بده / بیا» برای پیشنهاد انجام کار.","Let's drink something.","Let's + فعل ساده برای پیشنهاد."]];

// ========== پایه هشتم - درس 1 ==========
words[9]=[["Iran is great!","ایران عالی است"],["South America","آمریکای جنوبی"],["cousin","پسر عمو/ دختر عمو/ پسر دایی/ دختر دایی/ پسر خاله/ دختر خاله/ پسر عمه/ دختر عمه"],["Asian","آسیایی"],["North American","آمریکای شمالی"],["He speaks French, English, and a little Persian.","او به فرانسه، انگلیسی و کمی به فارسی صحبت می کند"],["I'm originally Iranian.","من اصالتا ایرانی هستم"],["Spanish","اسپانیاییها"],["Spain","اسپانیا"],["South American","اهل آمریکای جنوبی"],["continent","قاره"],["Where is he from?","او اهل کجاست؟"],["North America","آمریکای شمالی"],["African","آفریقایی"],["Chinese","چینی"],["Australia","استرالیا"],["They're from Spain.","آنها اهل اسپانیا هستند"],["European","اروپایی"],["relative","خویشاوند"],["Africa","آفریقا"],["Iranian","ایرانی"],["She's from England.","او اهل انگلستان است"],["How do you like it in Iran?","ایران را چطور دیدی؟"],["Persian Gulf","خلیج فارس"],["Brazil","برزیل"],["France","فرانسه"],["Europe","اروپا"],["Are you from Iran?","آیا اهل ایران هستید؟"],["I live in France.","من در فرانسه زندگی می کنم"],["Iran","ایران"],["China","چین"],["Brazilian","برزیلی"],["He's from France.","او اهل فرانسه است"],["Where are they from?","آنها اهل کجا هستند؟"],["Asia","آسیا"],["British","بریتانیایی"],["guest","مهمان"],["nationality","ملیت"],["French","فرانسوی"],["country","کشور"],["Caspian Sea","دریای خزر"],["England","انگلستان"],["I love it.","من دوستش دارم"],["Australian","استرالیایی"],["It's a beautiful country.","این یک کشور زیباست"]];
grammar[9]=[["بیان ملیت و کشور","برای بیان اینکه شخص اهل کدام کشور است از کلمه from استفاده می‌شود.","I am from Iran.\nShe is from France.\nThey are from China.","ساختار: فاعل + am/is/are + from + کشور"],["منفی کردن جملات","برای منفی کردن کافی است پس از am, is, are از not استفاده کنیم.","You aren't from Spain.\nHe isn't from England.\nI'm not from China.","مخفف‌ها: isn't / aren't / Am not (مخفف ندارد)"],["سوالی کردن جملات","برای پرسشی کردن am, is, are را در ابتدای جمله می‌آوریم.","Are they from Spain?\nIs she from Iran?","با جابجایی فعل و فاعل، جمله سوالی می‌شود."],["پاسخ کوتاه","برای پاسخ کوتاه Yes یا No + عبارت مناسب.","Are they from Iran? Yes, they are. / No, they aren't.","در پاسخ کوتاه از ضمیر مناسب استفاده می‌شود."],["سوال با Where","برای پرسیدن مکان از Where استفاده می‌شود.","Where are you from?","در پاسخ از جملات مثبت استفاده می‌شود."],["بیان ملیت بدون from","برای بیان ملیت‌ها دیگر نباید از from استفاده کنیم.","They are Chinese.\nShe is Spanish.","مقایسه: You are from Brazil. / You are Brazilian."]];

// ========== پایه هشتم - درس 2 ==========
words[10]=[["What days do you play sports?","چه روزهایی ورزش می کنی؟"],["What days do you go shopping?","چه روزهایی خرید می روی؟"],["When can you start?","از کی می توانی شروع کنی؟"],["day","روز"],["midnight","نیمه شب"],["What days do you go to school?","چه روزهایی به مدرسه می روی؟"],["go to library","به کتابخانه رفتن"],["visit relatives","سر زدن به فامیل"],["That's fine.","خوبه"],["when","چه زمانی"],["why","چرا"],["I go to the gym on Sundays and Tuesdays.","من یکشنبه ها و سه شنبه ها به باشگاه می روم"],["sunrise","طلوع خورشید"],["midday","ظهر"],["I stay at home and relax.","من خانه می مانم و استراحت می کنم"],["night","شب"],["climb a mountain","کوهنوردی کردن"],["I'll let her know.","به او می گویم"],["relax","آرامیدن"],["noon","ظهر"],["stay","ماندن"],["weekend","آخر هفته"],["... is not very good at English.","زیاد انگلیسی اش خوب نیست"],["Every weekday.","هر روز هفته"],["sir","آقا"],["go to the gym","رفتن به باشگاه"],["play sports","ورزش کردن"],["go to school","به مدرسه رفتن"],["gym","باشگاه"],["madam","خانم"],["What days do you study English?","چه روزهایی زبان (انگلیسی) می خوانی؟"],["well","خب"],["watch TV","تلویزیون تماشا کردن"],["weekday","روز هفته"],["sunset","غروب خورشید"],["week","هفته"],["How about Friday mornings?","صبح های جمعه چطور؟"],["study lessons","درس خواندن"],["That sounds great!","عالی به نظر می رسد"],["What days do you go to the library?","چه روزهایی به کتابخانه می روی؟"],["What do you do in the afternoons?","بعد از ظهرها چه کار می کنی"]];
grammar[10]=[["زمان حال ساده (Simple Present)","برای فعالیت‌هایی که تداوم دارند و بصورت روتین انجام می‌شوند.","Ali takes a shower every day.\nI usually read the newspaper in the morning.","دو کاربرد اصلی: عادات روزانه و حقایق طبیعی"],["سوالی کردن زمان حال ساده","برای سوالی کردن از دو فعل کمکی Do و Does استفاده می‌شود.","Does she drink tea very often?\nDo I come from Iran?\nDo workers clean here every Monday?","برای سوم شخص مفرد Does و بقیه Do."],["منفی کردن زمان حال ساده","برای منفی کردن از Do not و Does not استفاده می‌شود.","He doesn't work for I.R.I.B.\nYour dog doesn't bark loudly.","مخفف‌ها: don't / doesn't"],["پرسیدن فعالیت‌های هفتگی","برای پرسیدن فعالیت‌ها از الگوی What do you do استفاده می‌شود.","What do you do in the mornings?\nI go to school.","برای زمان یا روز: When / What days do you...?"],["حروف اضافه زمان","قبل از ایام هفته On و قبل از صبح و ظهر و عصر In.","On Friday\nIn the morning","نکته: دو روز آخر هفته = Weekend / پنج روز دیگر = Weekdays"]];

// ========== پایه هشتم - درس 3 ==========
words[11]=[["play volleyball","والیبال بازی کردن"],["Who can work with a computer?","کی بلد است با کامپیوتر کار کند؟"],["Can you make a cake?","می توانی کیک درست کنی؟"],["Can I see your photos?","می توانم عکس هایت را ببینم؟"],["Who can draw?","چه کسی می تواند نقاشی بکشد؟"],["Are you good at drawing?","آیا نقاشی ات خوب است؟"],["Are you good at searching the Web?","آیا شما در جستجو در فضای اینترنت خوب هستید؟"],["act in movies","بازی کردن در فیلم‌های سینمایی"],["drawing","طراحی (هنر)"],["Are they good at swimming?","آیا شنا کردن آنها خوب است؟"],["photo","عکس"],["Is he good at playing football?","آیا او خوب فوتبال بازی می‌کند؟"],["ride a horse","اسب سواری کردن"],["play basketball","بسکتبال بازی کردن"],["Who is good at telling stories?","کی خوب می تواند داستان بگوید؟"],["wow!","وای"],["Why not?","چرا که نه؟"],["recite the Holy Quran","از حفظ خواندن قرآن مجید"],["do a puzzle","پازل درست کردن"],["Excuse me, I have a question.","ببخشید، من یک سوال دارم"],["Who can play tennis?","کی می تواند تنیس بازی کند؟"],["tell a story","داستان گفتن"],["Can they play basketball?","آیا آنها می توانند بسکتبال بازی کنند؟"],["play badminton","بدمینتون بازی کردن"],["run","دویدن"],["Can she search the Web?","آیا او می تواند در اینترنت جستجو کند؟"],["good","خوب"],["swim","شنا کردن"],["Are you good at riding a bicycle?","آیا دوچرخه سواری ات خوب است؟"],["Can you ride a bicycle?","می توانید دوچرخه سواری کنید؟"],["Is she good at cooking?","آیا آشپزی او خوب است؟"],["draw","نقاشی کشیدن"],["Come to my house this afternoon.","امروز بعد از ظهر به خانه ی من بیا"],["take photos","عکس گرفتن"],["Can he do a puzzle?","آیا او می تواند پازل را تکمیل کند؟"],["ability","مهارت"],["I'm not good at drawing.","من نقاشی ام خوب نیست"],["Can you draw?","می توانی نقاشی بکشی؟"],["Who is good at riding a bicycle?","چه کسی دوچرخه سواری اش خوب است؟"],["work with a computer","با کامپیوتر کار کردن"],["Who can take photos?","کی می تواند عکس بگیرد؟"],["Your drawing is very good.","نقاشی تو خیلی قشنگ است"],["draw a picture","نقاشی کشیدن"],["play ping-pong","پینگ پنگ بازی کردن"],["make tea","چای درست کردن"],["I can take good photos.","من می توانم خوب عکس بگیرم"],["speak","صحبت کردن"],["I can't make it today.","من امروز نمی توانم (بیایم)"],["ride a bicycle","دوچرخه سواری کردن"],["play tennis","تنیس بازی کردن"],["play chess","شطرنج بازی کردن"],["type","تایپ کردن"],["read","خواندن"],["puzzle","پازل"],["You can bring your drawing book, too.","می توانی دفتر نقاشی ات را هم همراه خودت بیاوری"]];
grammar[11]=[["صفت‌های ملکی","صفت‌های ملکی برای نشان دادن مالکیت.","my - your - his - her - its - our - their","I-my / you-your / he-his / she-her / it-its / we-our / they-their"],["بیان توانایی با Good at","برای بیان توانایی از am/is/are + good at + فعل-ing.","I am good at drawing.\nHe is good at taking photos.","Good at + اسم یا فعل-ing برای مهارت."],["بیان توانایی با Can","برای بیان توانایی از فعل کمکی Can استفاده می‌شود.","I can draw.\nHe can take photos.\nThey can play basketball.","ساختار: فاعل + can + فعل ساده"]];

// ========== پایه هشتم - درس 4 ==========
words[12]=[["drugstore","داروخانه"],["You should go home and rest.","باید به خانه بروی و استراحت کنی"],["health problem","مشکل سلامتی"],["You should rest.","باید استراحت کنی"],["Thanks for your help.","ممنون بابت کمک شما"],["I'll talk to your teacher.","من با معلمت صحبت خواهم کرد"],["stomachache","دل درد"],["cough","سرفه"],["What's the matter?","چه شده است؟"],["patient","مریض"],["advice","نصیحت"],["I have a sore throat.","من گلودرد دارم"],["Why don't you see a doctor?","چرا نمی روی دکتر؟"],["You have sore eyes, too.","چشم هایت هم که خون افتاده است"],["Go to the dentist.","به دندانپزشکی برو"],["What is the problem?","چه مشکلی پیش آمده است؟"],["have a fever","تب داشتن"],["earache","گوش‌درد"],["What's wrong?","چه شده است؟"],["running nose","آبریزش بینی"],["Let's go to the office and call your parents first.","بیا اول به دفتر برویم و به پدر و مادرت زنگ بزنیم"],["Why don't you get some rest?","چرا کمی استراحت نمی کنی؟"],["cold","سرماخوردگی"],["Is she all right?","آیا او حالش خوب است؟"],["sore throat","گلودرد"],["Are you OK?","خوبی؟"],["I'll be back in a minute.","من یک دقیقه ای بر می گردم"],["You should see a doctor.","باید بروی دکتر"],["toothache","دندان درد"],["rest","استراحت کردن"],["I have a headache.","سردرد دارم"],["headache","سردرد"],["measles","سرخک"],["health","سلامت"],["have a temperature","تب داشتن"],["backache","کمردرد"],["We have one more class.","ما یک کلاس دیگر هم داریم"],["sore eyes","چشم های خون افتاده"],["Czech","اهل جمهوری چک"],["I have a toothache.","دندان درد دارم"],["Is he OK?","آیا او حالش خوب است؟"],["I have a cold.","سرما خورده ام"],["parent","والد"],["hospital","بیمارستان"],["don't worry.","نگران نباش"],["quiet","ساکت"],["sneeze","عطسه"],["Be quiet!","ساکت باشید"],["flu","آنفلوآنزا"],["mumps","اوریون"],["I have a running nose.","آبریزش بینی دارم"]];
grammar[12]=[["پرسش درباره سلامت","سه جمله برای جویا شدن احوال.","What's wrong?\nWhat's the matter?\nWhat's the problem?","در جواب مشکل سلامتی را بیان می‌کنیم."],["احوالپرسی با OK / all right","با استفاده از فعل‌های am/is/are.","Are you OK?\nIs he all right?","در جواب از No استفاده می‌کنیم."],["توصیه برای مشکلات سلامتی","پس از شنیدن مشکل، توصیه مناسب ارائه می‌دهیم.","I have a toothache. → Go to the dentist.\nI have a running nose. → Why don't you get some rest?","الگوها: Go to ... / You should ... / Why don't you ...?"],["نکته تلفظی","در بعضی کلمات ch صدای «ک» می‌دهد.","school - backache - mechanic - zucchini - stomachache","ea صدای «اِ»: headache - bread - health - sweater - weather"]];

// ========== پایه هشتم - درس 5 ==========
words[13]=[["mosque","مسجد"],["actually","درواقع"],["cinema","سینما"],["minaret","مناره"],["center","مرکز"],["east","شرق"],["zoo","باغ وحش"],["stadium","ورزشگاه"],["Isfahan's an old city in the center of Iran.","اصفهان شهری قدیمی در مرکز ایران است"],["many","چندین"],["boulevard","بلوار"],["What's it like?","چگونه است؟"],["old","قدیمی"],["Please say it again.","لطفا دوباره بگو"],["restaurant","رستوران"],["location","موقعیت"],["palace","کاخ"],["Where is it?","آن کجاست؟"],["I should see the city soon.","من به زودی از شهر دیدن خواهم کرد"],["bridge","پل"],["city","شهر"],["shrine","حرم"],["building","ساختمان"],["west","غرب"],["Are there any museums?","آیا موزه هم دارد؟"],["What is it famous for?","آن (شهر) برای چه چیزی معروف است؟"],["We can have special food downtown.","ما می توانیم در مرکز شهر غذای ویژه بخوریم"],["church","کلیسا"],["capital","پایتخت"],["Tell me about Isfahan.","راجع به اصفهان برایم بگو"],["north","شمال"],["museum","موزه"],["tourist","گردشگر"],["downtown","مرکز شهر"],["special","خاص"],["metro","مترو"],["clean","تمیز"],["It's a big and clean city.","آن شهری بزرگ و تمیز است"],["big","بزرگ"],["park","پارک"],["south","جنوب"],["store","مغازه"],["famous","مشهور"],["Isfahan is very famous for its mosques and palaces.","اصفهان بابت مساجد و کاخ هایش بسیار مشهور است"],["train station","ایستگاه راه آهن"],["near","نزدیک"],["Any famous buildings?","ساختمان های معروفی دارد؟"],["bus station","ایستگاه اتوبوس"],["airport","فرودگاه"],["north-east","شمال شرق"],["north-west","شمال غرب"],["south-east","جنوب شرقی"],["south-west","جنوب غربی"]];
grammar[13]=[["پرسش مکان و موقعیت","برای پرسیدن مکان شهر از Where is.","Where is Mashhad?\nIt's in the north-east of Iran.","برای پاسخ به مکان جغرافیایی."],["پرسش شکل ظاهری شهر","برای پرسیدن شکل ظاهری از What's it like?.","What's Tabriz like?\nIt's big and old.","در پاسخ به مشخصات ظاهری اشاره می‌شود."],["پرسش وجود امکانات","برای پرسیدن امکانات از Is there / Are there.","Is there a stadium?\nAre there any museums?","پاسخ: Yes, there is. / No, there isn't."],["پرسش شهرت شهر","برای پرسیدن شهرت از What is famous for?.","What is Isfahan famous for?\nIt's famous for its old mosques.","نکته تلفظی: th صدای «ث» یا «ذ»."]];

// ========== پایه هشتم - درس 6 ==========
words[14]=[["village","روستا"],["wind","باد"],["What's the people's job?","شغل مردم (آن شهر) چیست؟"],["It sounds to be a very interesting place.","به نظر می رسد مکان بسیار جالبی است"],["hen","مرغ"],["winter","زمستان"],["fall","پاییز"],["Can you give me some examples?","می توانید چند مثال برای من بزنید؟"],["icy","یخزده"],["hot","داغ"],["raise","پرورش دادن"],["rain","باران"],["cow","گاو"],["Are there many people in the village?","آیا مردم زیادی در روستا زندگی می کنند؟"],["It's a mountain village with many trees and flowers.","آن یک روستای کوهستانی با درختان و گل های بسیار است"],["What's the weather like in ...?","آب و هوا در ... چگونه است؟"],["summer","تابستان"],["tree","درخت"],["warm","گرم"],["cold","سرد"],["farm","مزرعه"],["spring","بهار"],["hill","تپه"],["Are there any fields?","آیا مزارع هم دارد؟"],["thermometer","دماسنج"],["weather","آب‌وهوا"],["field","مزرعه"],["There's a lot of wind in summer, fall and winter.","در تابستان، پاییز و زمستان باد بسیار زیاد می‌وزد"],["Is it near the city?","آیا نزدیک شهر است؟"],["flower","گل"],["Is it cold in winter?","آیا در زمستان سرد می‌شود؟"],["Is there much rain in spring?","آیا در بهار باران زیاد می‌بارد؟"],["dry","خشک"],["rainy","بارانی"],["Is there a river?","آیا رودخانه دارد؟"],["animal","حیوان"],["interesting","جالب"],["sunny","آفتابی"],["plow","گاو آهن"],["place","مکان"],["horse","اسب"],["mountain","کوه"],["chicken","مرغ"],["Where are you from?","شما اهل کجا هستید؟"],["It's famous for its sunflower fields.","آنجا به خاطر مزارع گل های آفتابگردانش معروف است"],["river","رود"],["cattle","گاوها (اعم از نر و ماده)"],["dog","سگ"],["sunflower","آفتابگردان"],["What about the weather?","آب و هوایش چطور است؟"],["snowy","برفی"],["very","خیلی"],["tractor","تراکتور"],["They work on farms and raise animals.","آنها در مزرعه کار می کنند و دام پرورش می دهند"]];
grammar[14]=[["پرسش آب و هوا","از What's the weather like.","What's the weather like in Rasht?","در جواب It's + صفت آب و هوا."],["پرسش آب و هوا در فصل‌ها","از Is it + آب و هوا + in + فصل.","Is it snowy in winter?\nYes, it is. / No, it isn't.","در پاسخ از Yes/No استفاده می‌شود."],["توصیف روستا","به فضاها و امکانات طبیعی اشاره می‌شود.","What's Amir Abad like?\nIt's a mountain village with many farms and a river.","شغل مردم: They work on farms and raise animals."],["عبارات جایگزین","از How about / What about برای جلوگیری از تکرار.","What's the weather like in spring?\nHow about winter?","th صدای «ذ»: mother - father - brother - with - this - they - there - that - the - weather"]];

// ========== پایه هشتم - درس 7 ==========
words[15]=[["poem","شعر"],["horse riding","اسب سواری"],["reading","مطالعه"],["What do you like to do in your free time?","دوست دارید در اوقات فراغت خود چه کاری کنید؟"],["playing computer games","بازی کامپیوتری بازی کردن"],["sometimes","گاهی"],["What's your hobby?","سرگرمی شما چیست؟"],["What sort of things do you read?","چه جور چیزهایی میخوانی؟"],["Do you have any hobbies?","آیا هیچ سرگرمی ای داری؟"],["watching movies","فیلم تماشا کردن"],["walking in the park","قدم زدن در پارک"],["magazine","مجله"],["sports news","خبر ورزشی"],["What do you do as a hobby?","برای سرگرمی چه کاری انجام می دهی؟"],["usually","معمولاً"],["I watch movies as a hobby.","من به عنوان سرگرمی تلویزیون تماشا می کنم"],["playing tennis","تنیس بازی کردن"],["search","جستجو کردن"],["skiing","اسکی"],["listening to the radio","گوش دادن به رادیو"],["fishing","ماهی گیری"],["Net","اینترنت"],["Do you like reading?","مطالعه کردن را دوست داری؟"],["I don't have any hobbies.","من هیچ سرگرمی ای ندارم"],["shopping","خرید"],["hobby","سرگرمی"],["free time","وقت آزاد"],["going to the movies","رفتن به سینما"],["I love reading.","من عاشق مطالعه هستم"],["working in the garden","در باغ کار کردن"],["enjoy","لذت بردن"],["browsing the internet","در اینترنت گشت زدن"],["I usually go to the gym in my free time.","من معمولا در وقت آزادم به باشگاه می روم"],["What do you do in your free time?","در اوقات فراغت خود چه می کنید؟"],["fire service","سازمان آتش‌نشانی"]];
grammar[15]=[["وقت آزاد (Free Time)","برای صحبت در مورد سرگرمی‌ها و اوقات فراغت.","What do you do in your free time?\nWhat do you like to do in your free time?","در پاسخ به فعالیت‌های سرگرمی‌کننده اشاره می‌شود."]];

// ========== پایه نهم - درس 1 ==========
words[16]=[["patient","صبور"],["bit","کم"],["personality","شخصیت"],["hard-working","کوشا"],["neat","مرتب و منظم"],["careful","مراقب"],["What's he like?","او چه جور آدمی است؟"],["kind","مهربان"],["how","چطور"],["talkative","پرحرف"],["also","همچنین"],["careless","بی‌دقت"],["clever","باهوش"],["Is he hard-working too?","آیا کوشا هم هست؟"],["pleasant","خوشایند"],["happy","خوشحال"],["lazy","تنبل"],["shy","خجالتی"],["He always helps me with my lessons.","او همیشه به من در درس هایم کمک می کند"],["What is your friend like?","دوستت چه جور آدمی است؟"],["cruel","بی‌رحم"],["rude","بی‌ادب"],["I do my homework.","من تکالیفم را انجام می دهم"],["helpful","مفید"],["generous","بخشنده"],["friendly","دوستانه"],["Let me check it in the dictionary.","اجازه بدهید این (واژه) را در فرهنگ لغت چک کنم"],["best friend","بهترین دوست"],["everybody","همه"],["member","عضو"],["great","عالی"],["polite","مؤدب"],["Oh, he is really great!","اوه! او واقعا آدم خوبی است"],["some","بعضی (از)"],["upset","ناراحت"],["company","شرکت"],["nervous","مضطرب"],["She works for a company.","او برای یک شرکت کار می کند"],["And he's always very helpful.","و او همیشه خیلی کمک کننده است"],["Who is your best friend at school?","چه کسی دوست صمیمی تو در مدرسه است؟"],["selfish","خودخواه"],["funny","بامزه"],["serious","جدی"],["brave","شجاع"],["He's clever and kind.","او باهوش و مهربان است"],["always","همیشه"],["angry","عصبانی"],["homework","تکلیف منزل"]];
grammar[16]=[["آموزش فعل to be","فعل to be در زمان حال ساده صرف می‌شود.","I am a student.\nHe is a teacher.\nThey are happy.","I am / You are / He is / She is / It is / We are / You are / They are"],["حالت منفی to be","بعد از to be کلمه not قرار می‌گیرد.","I am not talkative.\nHe is not shy.\nThey are not rude.","مخفف‌ها: I'm not / He isn't / She isn't / They aren't"],["حالت سوالی to be","جای to be و فاعل را عوض می‌کنیم.","Am I careful?\nIs he careful?\nAre we careful?","در پاسخ از Yes/No استفاده می‌شود."],["There is / There are","برای بیان وجود.","There is a book on the table.\nThere are two apples on the table.","برای بیش از یکی از There are."],["ساختارهای اختصاری","برای سرعت بیشتر در گفتار.","I am = I'm / He is = He's / It is = It's / We are = We're","نکته: I am not → I'm not"]];

// ========== پایه نهم - درس 2 ==========
words[17]=[["say prayers","نماز خواندن"],["land","فرود آمدن"],["Hope you enjoy your stay in Tehran.","امیدوارم از اقامت تان در تهران لذت ببرید"],["check the timetable","چک کردن برنامه حرکت"],["around the World","دور دنیا"],["hope","امیدوار بودن"],["of course","البته"],["check the passport","گذرنامه چک کردن"],["book a hotel","هتل رزرو کردن"],["make a voyage","سفر دریایی رفتن"],["baggage reclaim","محل دریافت بار (فرودگاه)"],["suitable","مناسب"],["My wife and I are visiting Tehran for three days.","من و همسرم به مدت سه روز از تهران بازدید می کنیم"],["guess","حدس زدن"],["key","کلید"],["novel","رمان"],["map","نقشه"],["Germany","آلمان"],["Arabic","زبان عربی"],["leg","پایه"],["buy a ticket","بلیط خریدن"],["talk to a receptionist","با متصدی پذیرش صحبت کردن"],["I have a reservation here.","من اینجا (اتاق) رزرو کرده ام"],["Are you staying here for two nights?","آیا به مدت دو شب اینجا می مائید؟"],["car","خودرو"],["pay toll","عوارضی پرداخت کردن"],["Are you working with the computer now?","آیا الان داری با کامپیوتر کار می کنی؟"],["letter","نامه"],["board the plane","سوار هواپیما شدن"],["German","آلمانی"],["take off","از زمین بلند شدن (هواپیما)"],["Here is her passport.","بفرمایید، این هم پاسپورت او"],["pray","دعا کردن"],["take an express train","قطار سریع السیر سوار شدن"],["wheel","چرخ"],["guide book","کتابچه راهنما"],["I need to check her passport.","من باید گذرنامه شان را چک کنم"],["pack for a trip","برای سفر وسیله گرفتن"],["This is your key.","این کلید شماست"],["reservation","رزرو"],["fill out the form","فرم پر کردن"],["possible","امکان پذیر"],["tourist","گردشگر"],["check in","پذیرش شدن"],["here","اینجا"],["short story","داستان کوتاه"],["Is it possible to book it online?","آیا ممکن است که آنلاین رزرو کنی؟"],["I'm searching for a hotel in ...","من دارم دنبال هتلی در ... می گردم"],["weigh the baggage","بار وزن کردن"],["She's standing over there, by the gift shop.","او آنجا ایستاده است، کنار کادو سرا"],["exchange money","پول و ارز تبدیل کردن"],["I see!","متوجه شدم"],["gift shop","کادوسرا"],["online","آنلاین"]];
grammar[17]=[["زمان حال استمراری (Present Continuous)","برای بیان کاری که در لحظه صحبت در حال انجام است.","I am eating dinner.\nShe is writing a letter.\nThey are playing football.","ساختار: فاعل + am/is/are + فعل + ing"],["سوالی کردن حال استمراری","فاعل را با to be جا به جا می‌کنیم.","Am I running?\nIs he sleeping?\nAre they singing?","در پاسخ از Yes/No استفاده می‌شود."],["منفی کردن حال استمراری","بعد از to be از not استفاده می‌شود.","I am not cooking.\nHe isn't coming.\nThey aren't watching TV.","مخفف‌ها: I'm not / He isn't / She isn't / They aren't"],["نکات افزودن ing","اگر فعل به e ختم شود، e حذف می‌شود.","write → writing\nsit → sitting","swim → swimming / run → running"],["نشانه‌های حال استمراری","now, right now, at this moment, look, listen, still, just, at present","Look! There is a cat in the kitchen.\nI'm doing my homework right now.","نشانه‌ها در جمله به کار می‌روند."],["مالکیت با 's","برای مالکیت از آپاستروف s استفاده می‌شود.","Dog's collar\nSister's backpack","برای جمع: sisters' backpacks"],["مالکیت با of","برای تعلق شی به شی دیگر.","The name of that street\nThe roof of the house","of برای تعلق شی به شی."]];

// ========== پایه نهم - درس 3 ==========
words[18]=[["holiday","روز تعطیل"],["Do you and your cousins set the Haft Seen table?","آیا شما و خویشاوندان شما سفره هفت سین می چینند؟"],["celebrate a religious holiday","تعطیلات مذهبی را جشن گرفتن"],["I just love New Year holidays!","من واقعا تعطیلات سال نو را دوست دارم"],["Do you get New Year gifts too?","آیا هدیه ی سال نو هم می گیرید؟"],["set the table","چیدن میز غذا"],["Commemorate NE martyrs","گرامی داشت شهدای انرژی هسته ای"],["They say their Eid prayers before noon.","آنها نماز عید شان را قبل از ظهر می خوانند"],["Do young children color the eggs?","آیا بچه های کوچک تخم مرغ رنگ می کنند؟"],["clear the table","میز غذا را جمع کردن"],["I really like Fajr Film Festival.","من واقعا جشنواره فیلم فجر را دوست دارم"],["go out on Nature Day","بیرون رفتن در روز طبیعت"],["watch fireworks","آتش بازی تماشا کردن"],["watch military parade","تماشا کردن رژه نظامی"],["In all Muslim countries people hold the same ceremony.","در تمام کشورهای اسلامی مسلمانان مراسم یکسانی برگزار می کنند"],["gold fish","ماهی قرمز"],["Does he recite the Holy Quran at the turn of the year?","آیا او در آغاز سال (جدید) قرآن مجید قرائت می کند؟"],["Turkey","ترکیه"],["wear special clothes","لباس‌های مخصوص پوشیدن"],["Nature Day","روز طبیعت"],["Happy New Year!","سال نو مبارک"],["national","ملی"],["dish","ظرف"],["Islamic-Iranian culture","فرهنگ اسلامی-ایرانی"],["sing the national anthem","خواندن سرود ملی"],["New Year","سال نو"],["clothes","لباس"],["fun","سرگرمی"],["normally","معمولاً"],["bake a cake","کیک پختن"],["gift","کادو"],["Muslim","مسلمان"],["Do you buy new clothes for the New Year?","آیا برای سال جدید لباس های نو می خرید؟"],["We usually get money.","ما معمولا پول می گیریم"],["meal","وعده غذایی"],["make lunch","ناهار درست کردن"],["On Fitr Eid, Muslims don't fast.","در عید فطر، مسلمانان روزه نمی گیرند"],["international","بین المللی"],["hold a ceremony","جشن برپا کردن"],["fast","روزه گرفتن"],["Does your grandmother cook the New Year meal?","آیا مادربزرگت غذای سال نو را درست می کند؟"],["We always go to my grandparents' houses.","ما همیشه به خانه ی پدر بزرگ و مادربزرگم می رویم"],["Fitr Eid is an important religious holiday.","عید فطر یک تعطیلات مذهبی مهم است"],["Do Chinese people buy gold fish for the New Year?","آیا چینی ها برای سال نو ماهی قرمز می خردند؟"],["grandparent","پدربزرگ یا مادربزرگ"],["Islamic revolution anniversary","سالگرد انقلاب اسلامی"],["It's fun!","خوش می گذرد"],["make dinner","شام درست کردن"],["We normally visit our relatives in Norooz.","ما معمولا در نوروز به دید و بازدید فامیل می رویم"],["Wish you a great holiday!","برای شما تعطیلات خوبی آرزو دارم"],["eat nuts","آجیل خوردن"],["ceremony","مراسم"],["festival","جشنواره"],["read poems of Hafiz","خواندن اشعار حافظ"]];
grammar[18]=[["زمان حال ساده (Simple Present)","برای نشان دادن کاری که در زمان حال تکراری اتفاق می‌افتد.","He plays football every Tuesday.\nThe bus leaves at half past four.","کاربردها: عادت‌ها، حقایق علمی، برنامه‌های آینده"],["سوم شخص مفرد","برای he/she/it به فعل s یا es اضافه می‌شود.","I speak → He speaks\nI wash → She washes","sh, ch, z, ss, x → es / y با صدا دار → ies"],["منفی و سوالی","از Do/Does استفاده می‌شود.","I do not speak.\nHe does not speak.\nDo I speak?\nDoes he speak?","Does برای سوم شخص مفرد و Do برای بقیه."],["قیدهای تکرار","نشان‌دهنده میزان تکرار عمل.","always (100%) - usually - often - sometimes - rarely - never (0%)","I usually play football with my friends."],["صفت‌های ملکی","قبل از اسم می‌آیند و مالکیت را نشان می‌دهند.","My car is in the yard.\nHis cat is quiet.","my, your, his, her, its, our, their"]];

// ========== پایه نهم - درس 4 ==========
words[19]=[["recharge the e-ticket","شارژ مجدد بلیت الکترونیک"],["gas station","جایگاه سوخت"],["He often plays outside.","او اغلب بیرون (از خانه) بازی می کند"],["What does a firefighter do?","یک آتش نشان چه کار می کند؟"],["never","هرگز"],["Is there a fire station near here?","آیا در نزدیکی اینجا اداره آتش نشانی هست؟"],["What is her job?","شغل او چیست؟"],["Thanks a lot!","خیلی ممنون"],["fast","سریع"],["When is the break?","زنگ تفریح کی است؟"],["When does a firefighter go to work?","یک آتش نشان چه زمانی به سرکار می رود؟"],["How do you come to school?","شما چطور به مدرسه می آیید؟"],["firefighter","آتش نشان"],["fire station","ایستگاه آتش نشانی"],["cheap","ارزان"],["stamp","تمبر"],["send an e-mail","ایمیل فرستادن"],["open an account","حساب (بانکی) باز کردن"],["Because it's fast and cheap.","چون سریع و ارزان است"],["I'm lost.","من گم شده ام"],["get off a bus","از اتوبوس پیاده شدن"],["envelope","پاکت (نامه)"],["help charity","به (موسسه) خیریه کمک کردن"],["donate blood","خون اهدا کردن"],["take out money","پول برداشت کردن"],["break","وقت استراحت"],["What can I do for you?","چه کاری از دست من بر می آید؟"],["Who helps lost children?","چه کسی به کودکان گمشده کمک می کند؟"],["They never come late.","آنها هیچوقت دیر نمی آیند"],["hire a taxi","تاکسی گرفتن"],["because","چون"],["wake up","از خواب بیدار شدن"],["Actually it's near here.","درواقع آن نزدیک به اینجاست"],["service","خدمت"],["What time does it open?","چه ساعتی باز می شود؟"],["I can take you home.","من می توانم تو را به خانه برسانم"],["often","اغلب"],["He puts out fire and saves people's lives.","او آتش را خاموش می کند و جان مردم را نجات می دهد"],["Mandarin","زبان ماندارین"],["corner","گوشه"],["And is it an easy job?!","و آیا آن شغل آسانی است؟"],["keep the city clean","شهر را تمیز نگه داشتن"],["What's your favorite job?","شغل مورد علاقه ی شما چیست؟"],["post office","اداره پست"],["I like to be a firefighter.","من دوست دارم آتش نشان شوم"],["I think he goes to work on shifts.","من فکر می کنم او شیفتی کار می کند"],["I take a bus.","من سوار اتوبوس می شوم"],["She always studies hard.","او همیشه بسیار درس می خواند"],["bring to the ER","به اورژانس آوردن"],["postcard","کارت پستال"],["do voluntary work","کار داوطلبانه انجام دادن"],["shift","شیفت"],["Where does he work?","او کجا کار می کند؟"],["get on a bus","سوار اتوبوس شدن"],["call the emergency","به اورژانس زنگ زدن"],["It's just round the corner.","آن درست سر پیچ است"],["Why does he go to work by bus?","چرا او با اتوبوس به سر کار می رود؟"],["You can get them from a post office.","می توانید آنها را از اداره پست بخرید"],["put out fire","آتش خاموش کردن"]];
grammar[19]=[["Wh Questions","کلمات پرسشی برای گرفتن اطلاعات.","What → چه چیز\nWhere → کجا\nWhen → چه وقت\nWho → چه کسی\nWhy → چرا\nHow → چطور\nHow many → چندتا\nHow much → چه مقدار","در پاسخ نمی‌توان از Yes/No استفاده کرد."],["دسته اول کلمات پرسشی","بعد از کلمه پرسشی، اسم سپس جمله سوالی.","How many books do you have?\nWhose pen is this?\nWhich one is your brother?","کلمات: How many, How much, Whose, Which"],["دسته دوم کلمات پرسشی","بعد از کلمه پرسشی، جمله سوالی.","What is your name?\nWhere do you live?\nWhen is your birthday?\nHow are you?","کلمات: What, What color, What time, What day, How, When, Where, Who, How old"],["قیدهای تکرار","برای مشخص کردن دفعات تکرار عمل.","I always watch TV in the morning.\nShe never listens to music.","قید تکرار قبل از فعل اصلی\nبعد از to be\nبین فعل کمکی و اصلی"]];

// ========== پایه نهم - درس 5 ==========
words[20]=[["see a war movie","یک فیلم جنگی دیدن"],["We can watch it together.","می توانیم با همدیگر تماشا کنیم"],["event","رویداد"],["update a blog","به روز کردن یک وبلاگ"],["look at the newsstand","به دکه روزنامه فروشی نگاهی انداختن"],["wonderful","شگفت‌انگیز"],["watch a quiz show","مسابقه تلویزیونی تماشا کردن"],["interview somebody","با شخصی مصاحبه کردن"],["attend","حضور داشتن"],["Change the TV channels","شبکه تلویزیون را عوض کردن"],["text a message","پیامک فرستادن"],["cartoon","کارتون"],["busy","پرمشغله"],["yesterday","دیروز"],["install an antivirus program","برنامه آنتی ویروس نصب کردن"],["I attended Fajr International Film Festival.","من در جشنواره بین المللی فیلم فجر شرکت کردم"],["movie","فیلم"],["amazing","شگفت‌آور"],["receive an e-mail","ایمیل دریافت کردن"],["It's amazing!","محشره"],["There is a football match on TV tonight.","امشب در تلویزیون مسابقه فوتبالی پخش می شود"],["How fantastic!","چقدر جالب"],["That's great!","عالیه"],["Well done!","آفرین"],["That's great news!","عجب خبر خوبی"],["use information technology","استفاده کردن از فناوری اطلاعات"],["Download something from the Internet","چیزی را از اینترنت دانلود کردن"],["Did you enjoy your weekend?","آیا از آخر هفته لذت بردی؟"],["text","پیام دادن"],["What a wonderful day!","چه روز قشنگی"],["excellent","عالی"],["comedy","نمایش خنده‌دار"],["install a computer dictionary","نصب کردن یک فرهنگ لغت کامپیوتری"],["media","رسانه"],["surf","جستجو کردن (در اینترنت)"],["fantastic","خارق‌العاده"],["I am also interested in its events and movies.","من همچنین علاقه مند به جشنواره ها و فیلم سینمایی هستم"],["Connect to the Internet","به اینترنت وصل شدن"],["Please buy some fruits.","لطفا مقداری میوه بخر"],["brilliant","عالی"],["participate in an online course","شرکت کردن در یک دوره آموزشی آنلاین"],["website","تارنما"],["report","گزارش"],["I get home at ...","من ساعت ... به خانه می رسم"],["Attend a TV program","در یک برنامه تلویزیونی شرکت کردن"],["Just a moment.","یک لحظه (صبر کنید)"],["That's really nice!","واقعا عالیه"],["That'll be all fun!","خیلی خوش خواهد گذشت"],["You can surf its website if you like.","می توانی اگر دوست داشتی سری به وب سایت آنجا بزنی"],["IT","فناوری اطلاعات"],["Could you please give me the website address?","می توانید لطفا آدرس وب سایت را به من بدهید؟"],["Did you watch the reports on TV last night?","آیا دیشب گزارش های تلویزیونی را تماشا کردی؟"]];
grammar[20]=[["زمان گذشته ساده (Simple Past)","برای بیان وقایعی که در گذشته اتفاق افتاده‌اند.","She met Sarah three weeks ago.\nI got up early, washed my face, ate breakfast, and went to school.","فعل‌ها به شکل گذشته در می‌آیند (با قاعده: ed- / بی‌قاعده: شکل دوم)"],["منفی و سوالی در گذشته ساده","برای منفی و سوالی از Did استفاده می‌شود.","I did not play.\nShe did not speak.\nDid I play?\nDid she speak?","بعد از Did فعل به شکل حال ساده می‌آید."],["فعل to be در گذشته","فعل to be در گذشته: was (مفرد) / were (جمع)","I was a student.\nWe were happy.\nWas I a student?\nWere you happy?","برای منفی: I was not / We were not"]];

// ========== پایه نهم - درس 6 ==========
words[21]=[["myself","ضمیر انعکاسی اول شخص مفرد"],["She burned her hand.","او دستش را سوزاند"],["head","سر"],["cookie","کلوچه"],["He hit his head on the door.","او سرش را به در زد"],["He has some bruises.","او چند کبودی دارد"],["find","پیدا کردن"],["He has a black eye.","او زیر چشمش کبود شده است"],["He has a scar.","او (جای) زخم دارد"],["Please stick a plaster on the wound.","لطفا روی زخم چسب زخم بچسبانید"],["Did you hurt your back?","به کمرت آسیب رسیده است؟"],["It sometimes happens.","برخی اوقات پیش می آید"],["plan","برنامه ریزی کردن"],["injury","صدمه"],["She cut her finger.","او انگشتش را برید"],["to have an accident","تصادف کردن"],["fall down","به زمین افتادن"],["school trips","اردوهای مدرسه"],["I don't like school trips.","من اردوهای مدرسه را دوست ندارم"],["That's too bad!","چقدر بد"],["Last summer I fell and broke my leg.","تابستان گذشته من افتادم و پایم شکست"],["We plan to go to the lake.","ما برنامه داریم به دریاچه برویم"],["Oh, does anyone have a plaster?","اوه، آیا کسی چسب زخم دارد؟"],["It hurts a lot.","خیلی درد می کند"],["take care","مراقب بودن"],["He broke his leg.","او پایش شکست"],["She takes care of her mother.","او از مادرش مراقبت می کند"],["I learnt how to take care of myself.","من یاد گرفتم چگونه از خودم مراقبت کنم"],["Let me see.","بگذار ببینم"],["He had a car crash.","او با اتومبیل تصادف کرد"],["It is bleeding.","دارد خون می آید"],["back","پشت"],["Here you are.","بفرمایید"],["I participated in Helal-e-Ahmar first aid classes.","من در کلاس های کمک های اولیه هلال احمر شرکت کردم"],["I hurt my knee.","زانویم صدمه دیده است"],["Can you give me some advice?","می توانید کمی من را نصیحت کنید؟"],["twist","پیچ خوردن"],["He has his leg in a cast.","او پایش را گچ گرفته است"],["after","بعد از"],["Just a second!","فقط یک لحظه"],["Do you want to come?","می خواهی بیایی؟"],["Please hurry up!","لطفا عجله کنید"],["I stayed home for two weeks!","من دو هفته در خانه ماندم"],["lake","دریاچه"],["leg","پا"],["I didn't know that.","من آن (موضوع) را نمی دانستم"],["She had a heart attack.","او سکته قلبی کرد"],["She takes care of her child.","او از کودکش مراقبت می کند"],["happen","اتفاق افتادن"],["break","شکستن"],["ankle","مچ پا"],["I twisted my ankle last winter.","زمستان گذشته مچ پایم پیچ خورد"],["cut","بریدن"]];
grammar[21]=[["ضمایر مفعولی","ضمایر مفعولی در نقش مفعول در جمله بکار می‌روند.","Give me a ring tomorrow.\nPlease tell him I phoned.\nI'm older than you.","me - you - him - her - it - us - them"],["جایگاه ضمایر مفعولی","بعد از فعل یا بعد از حرف اضافه قرار می‌گیرند.","Our teacher was angry with us.\nI'm looking for him.","در کنار and، ضمایر we و you مؤدبانه‌تر هستند: you and I, my father and I"]];

// ========== پایه دهم، یازدهم، دوازدهم (خلاصه) ==========
words[22]=[["Avicenna","ابن سینا"],["leopard","پلنگ"],["endangered","در معرض انقراض"],["wildlife","حیات وحش"],["nature","طبیعت"],["forest","جنگل"],["whale","نهنگ"],["tiger","ببر"],["dolphin","دلفین"],["giraffe","زرافه"],["wolf","گرگ"],["cheetah","یوزپلنگ"],["lion","شیر (حیوان)"],["zebra","گورخر"],["save","نجات دادن"],["protect","محافظت کردن"],["die out","منقرض شدن"],["destroy","نابود کردن"],["hunter","شکارچی"],["hurt","زخمی کردن"]];
grammar[22]=[["Present Perfect","برای تجربه‌ها یا اتفاق‌هایی که ارتباط با حال دارند.","Scientists have discovered new species.","have/has + past participle"],["Passive Voice","تمرکز روی عمل یا نتیجه.","Trees are planted every year.","be + past participle"],["First Conditional","برای شرط واقعی یا محتمل آینده.","If we protect nature, we will save animals.","If + present و will + verb"]];

words[23]=[["orbit","مدار"],["telescope","تلسکوپ"],["microscope","میکروسکوپ"],["planet","سیاره"],["Mars","مریخ"],["Neptune","نپتون"],["Saturn","زحل"],["Jupiter","مشتری"],["Uranus","اورانوس"],["Venus","زهره"],["Mercury","عطارد"],["moon","ماه"],["sun","خورشید"],["energy","انرژی"],["liquid","مایع"],["material","ماده"],["oxygen","اکسیژن"],["carbon dioxide","دی‌اکسید کربن"],["cell","سلول"],["organ","عضو"]];
grammar[23]=[["Relative Clauses","اطلاعات بیشتر درباره اسم.","Animals that live here need protection.","that و which"]];

words[24]=[["sadly","با ناراحتی"],["researcher","محقق"],["prophet","پیامبر"],["scientist","دانشمند"],["inventor","مخترع"],["invention","اختراع"],["laboratory","آزمایشگاه"],["invent","اختراع کردن"],["medicine","دارو"],["knowledge","دانش"],["success","موفقیت"],["successful","موفق"],["fortunately","خوشبختانه"],["solve","حل کردن"],["idea","ایده"],["thought","فکر"],["believe in","اعتقاد داشتن"],["give up","ترک کردن"],["pass away","فوت کردن"],["grow up","بزرگ شدن"]];
grammar[24]=[["Passive Voice","در مجهول مفعول به جایگاه فاعل.","The painting was created by a famous artist.","be + past participle"]];

words[25]=[["Peru","پرو"],["Chile","شیلی"],["Italy","ایتالیا"],["Egypt","مصر"],["Beijing","پکن"],["Great Wall","دیوار بزرگ چین"],["ancient","باستان"],["historical","تاریخی"],["traditional","سنتی"],["souvenir","سوغاتی"],["attraction","جذابیت"],["tourist","گردشگر"],["traveler","مسافر"],["sightseeing","بازدید از دیدنی‌ها"],["foreign","خارجی"],["visa","روادید"],["destination","مقصد"],["flight","پرواز"],["book","رزرو کردن"],["reservation","رزرو"]];
grammar[25]=[["Past Perfect","قبل از کار دیگری در گذشته.","She had finished her work before dinner.","had + past participle"],["Second Conditional","موقعیت‌های فرضی.","If I had more time, I would exercise every day.","If + past و would + verb"]];

words[26]=[["history","تاریخ"],["explanation","توضیح"],["interest","علاقه"],["disappear","ناپدید شدن"],["language","زبان"],["communicate","ارتباط برقرار کردن"],["native speaker","بومی"],["century","قرن"],["population","جمعیت"],["society","جامعه"],["university","دانشگاه"],["institute","موسسه"],["coffee","قهوه"],["experience","تجربه"],["understand","فهمیدن"],["use","استفاده کردن"],["available","در دسترس"],["communication","ارتباط"],["difference","تفاوت"],["valuable","باارزش"]];
grammar[26]=[["Present Perfect","رابطه بین گذشته و حال.","People have changed their lifestyles.","have/has + past participle"],["Reported Speech","نقل قول غیرمستقیم.","He said that he was tired.","زمان و ضمایر تغییر می‌کنند."]];

words[27]=[["normal","معمول"],["cure","درمان کردن"],["disease","بیماری"],["habit","عادت"],["lifestyle","سبک زندگی"],["effective","موثر"],["exercise","ورزش"],["diet","رژیم غذایی"],["stress","فشار عصبی"],["heart attack","حمله قلبی"],["healthy","سالم"],["unhealthy","ناسالم"],["prevent","جلوگیری کردن"],["improve","پیشرفت کردن"],["dangerous","خطرناک"],["addiction","اعتیاد"],["forbidden","ممنوع"],["cause","باعث شدن"],["reduce","کاهش دادن"],["increase","افزایش دادن"]];
grammar[27]=[["Modal Perfect","انتقاد از گذشته.","You should have studied more.","should have + past participle"],["Too / Enough","too یعنی بیش از حد، enough یعنی به اندازه کافی.","This exercise is too difficult for me.","صفات + too/enough"]];

words[28]=[["artist","هنرمند"],["artwork","اثر هنری"],["calligraphy","خوشنویسی"],["handicraft","صنایع دستی"],["creative","خلاق"],["skillful","ماهر"],["traditional","سنتی"],["culture","فرهنگ"],["identity","هویت"],["heritage","میراث"],["custom","سنت"],["ceremony","مراسم"],["bazaar","بازار"],["souvenir","سوغاتی"],["decorative","تزیینی"],["unique","منحصر به فرد"],["appreciate","قدر دانستن"],["reflect","بازتاب کردن"],["century","قرن"],["ancient","باستان"]];
grammar[28]=[["Passive with Modals","در مجهول همراه modal.","More energy should be saved.","modal + be + past participle"],["Causative","کاری که شخص دیگری انجام می‌دهد.","We had our solar panels installed.","have/get + object + past participle"]];

words[29]=[["emotion","احساس عاطفه"],["Reply","پاسخ دادن"],["Loving","مهربان، با محبت"],["Strength","قدرت، توانایی"],["Cruel","بی‌رحم، ظالم"],["Reader","خواننده"],["Elderly","سالمند"],["meaningful","هدفمند"],["heritage","میراث"],["handle","از پس کاری برآمدن"],["common","متداول"],["tool","ابزار"],["teenager","نوجوان"],["technology","فناوری"],["aloud","بلند"],["diploma","دیپلم"],["ethics","اخلاق"],["forgive","بخشیدن"],["grateful","سپاسگزار"],["respect","احترام گذاشتن"],["responsibility","مسئولیت"],["generation","نسل"],["kindness","مهربانی"],["failure","شکست"],["comprehension","فهم"],["polite","مؤدب"],["deserve","سزاوار بودن"],["principle","اصل اخلاقی"],["result","نتیجه"],["poetry","شعر"],["strategy","راهبرد"]];
grammar[29]=[["Present Perfect","برای تجربه‌ها و اتفاق‌ها.","Scientists have discovered new species.","have/has + past participle"]];

words[30]=[["generally","معمولاً"],["unknown","نامعلوم"],["level","سطح"],["antonym","متضاد"],["section","بخش"],["pronunciation","تلفظ"],["expression","اصطلاح"],["device","دستگاه"],["bilingual","دو زبانه"],["highlight","برجسته کردن"],["biography","زندگینامه"],["allow","اجازه دادن"],["whereas","در حالی که"],["term","اصطلاح"],["technical","فنی"],["treasure","گنج"],["intermediate","سطح متوسط"],["user","کاربر"],["phrase","عبارت"],["combination","ترکیب"],["pocket dictionary","فرهنگ لغت جیبی"],["origin","منشاء"],["pattern","الگو"],["magnet","آهن‌ربا"],["ocean","اقیانوس"],["element","عنصر"],["planet","سیاره"],["resource","منبع"],["insect","حشره"],["access","دسترسی"],["PC","کامپیوتر شخصی"],["provide","فراهم کردن"],["browser","مرورگر"],["commercial","تجاری"],["scale","مقیاس"],["compare","مقایسه کردن"],["symbol","نماد"],["recommend","پیشنهاد کردن"],["general","عمومی"]];
grammar[30]=[["Third Conditional","شرایط فرضی در گذشته.","If they had used renewable energy, they would have reduced pollution.","If + had + past participle و would have + past participle"],["Mixed Conditional","گذشته به نتیجه در زمان حال.","If we had protected forests, the air would be cleaner now.","If + had + past participle و would + verb"]];

words[31]=[["oxygen","اکسیژن"],["fan","پنکه"],["fossil fuel","سوخت فسیلی"],["necessary","لازم"],["Jupiter","مشتری"],["Saturn","زحل"],["reduce","کاهش دادن"],["variety","تنوع"],["chemical","شیمیایی"],["pollute","آلوده کردن"],["require","نیاز داشتن"],["radiation","تشعشع"],["nuclear","هسته‌ای"],["engine","موتور"],["battery","باتری"],["electrical","برقی"],["global warming","گرمایش جهانی"],["waste","پسماند"],["environment","محیط زیست"],["renewable","تجدیدپذیر"],["excellent","عالی"],["garbage","زباله"],["forever","برای همیشه"],["picnic","پیک‌نیک"],["apologize","عذرخواهی کردن"],["flashlight","چراغ قوه"],["source","منشأ"],["vacuum cleaner","جاروبرقی"],["nonrenewable","تجدیدنشدنی"],["format","فرمت"],["overcome","غالب آمدن"],["demand","تقاضا"],["burn","سوزاندن"],["consume","مصرف کردن"],["charge","شارژ کردن"],["balcony","بالکن"],["gasoline","بنزین"],["portable","قابل حمل"],["absorb","جذب کردن"],["practical","کاربردی"]];
grammar[31]=[["Future Perfect","تا زمان مشخصی در آینده کامل شده.","By 2030, scientists will have developed better technology.","will have + past participle"],["Noun Clauses","عبارت در نقش اسم.","What scientists discover can change our future.","عبارت اسمی"],["Inversion","بعد از قیدهای منفی جای فاعل و auxiliary تغییر می‌کند.","Never have we seen such a serious problem.","Inversion بعد از Never"]];

// پایان data.js
console.log("data.js loaded - words:",Object.keys(words).length,"grammar:",Object.keys(grammar).length);
